name = "leetcode"
version = "1.0.0"
repository = { type = "github", user = "kaganege", repo = "leetcode-gleam" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
